@echo off
cd /d D:\Users\Simon\Documents\familyhub-MVP
echo Checking status...
git status
echo Adding files...
git add .
echo Committing...
git commit -m "Implement UI fixes, Conflicts, Games Stats, Photos"
echo Pushing...
git push origin develop
pause
