// Mocks generated by Mockito 5.4.4 from annotations
// in familyhub_mvp/test/widgets/family_tree_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:familyhub_mvp/models/extended_family_hub_data.dart' as _i5;
import 'package:familyhub_mvp/models/hub.dart' as _i6;
import 'package:familyhub_mvp/models/user_model.dart' as _i9;
import 'package:familyhub_mvp/services/auth_service.dart' as _i7;
import 'package:familyhub_mvp/services/extended_family_hub_service.dart' as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i8;
import 'package:firebase_messaging/firebase_messaging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseMessaging_0 extends _i1.SmartFake
    implements _i2.FirebaseMessaging {
  _FakeFirebaseMessaging_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExtendedFamilyHubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtendedFamilyHubService extends _i1.Mock
    implements _i3.ExtendedFamilyHubService {
  MockExtendedFamilyHubService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.ExtendedFamilyHubData?> getExtendedFamilyData(String? hubId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExtendedFamilyData,
          [hubId],
        ),
        returnValue: _i4.Future<_i5.ExtendedFamilyHubData?>.value(),
      ) as _i4.Future<_i5.ExtendedFamilyHubData?>);

  @override
  _i4.Future<void> updateExtendedFamilyData(
    String? hubId,
    _i5.ExtendedFamilyHubData? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExtendedFamilyData,
          [
            hubId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setRelationship(
    String? hubId,
    String? memberId,
    _i5.RelationshipType? relationship,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRelationship,
          [
            hubId,
            memberId,
            relationship,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setPrivacyLevel(
    String? hubId,
    String? memberId,
    _i5.PrivacyLevel? privacyLevel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPrivacyLevel,
          [
            hubId,
            memberId,
            privacyLevel,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setMemberRole(
    String? hubId,
    String? memberId,
    _i5.ExtendedFamilyRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMemberRole,
          [
            hubId,
            memberId,
            role,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> inviteExtendedFamilyMember({
    required String? hubId,
    required String? email,
    _i5.RelationshipType? relationship,
    _i5.PrivacyLevel? privacyLevel = _i5.PrivacyLevel.minimal,
    _i5.ExtendedFamilyRole? role = _i5.ExtendedFamilyRole.viewer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteExtendedFamilyMember,
          [],
          {
            #hubId: hubId,
            #email: email,
            #relationship: relationship,
            #privacyLevel: privacyLevel,
            #role: role,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Hub>> getExtendedFamilyHubs() => (super.noSuchMethod(
        Invocation.method(
          #getExtendedFamilyHubs,
          [],
        ),
        returnValue: _i4.Future<List<_i6.Hub>>.value(<_i6.Hub>[]),
      ) as _i4.Future<List<_i6.Hub>>);

  @override
  _i4.Future<bool> canViewContent(
    String? hubId,
    String? contentType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canViewContent,
          [
            hubId,
            contentType,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseMessaging get messaging => (super.noSuchMethod(
        Invocation.getter(#messaging),
        returnValue: _FakeFirebaseMessaging_0(
          this,
          Invocation.getter(#messaging),
        ),
      ) as _i2.FirebaseMessaging);

  @override
  _i4.Stream<_i8.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i8.User?>.empty(),
      ) as _i4.Stream<_i8.User?>);

  @override
  _i4.Future<_i9.UserModel?> getCurrentUserModel() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserModel,
          [],
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<_i9.UserModel?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<_i9.UserModel?> registerWithEmailAndPassword(
    String? email,
    String? password,
    String? displayName, {
    String? familyId,
    String? creatorRelationship,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerWithEmailAndPassword,
          [
            email,
            password,
            displayName,
          ],
          {
            #familyId: familyId,
            #creatorRelationship: creatorRelationship,
          },
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> joinFamily(String? familyId) => (super.noSuchMethod(
        Invocation.method(
          #joinFamily,
          [familyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getFamilyInvitationCode() => (super.noSuchMethod(
        Invocation.method(
          #getFamilyInvitationCode,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> initializeFamilyId() => (super.noSuchMethod(
        Invocation.method(
          #initializeFamilyId,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> forceInitializeFamilyId() => (super.noSuchMethod(
        Invocation.method(
          #forceInitializeFamilyId,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #forceInitializeFamilyId,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> joinFamilyByInvitationCode(String? invitationCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinFamilyByInvitationCode,
          [invitationCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateFamilyIdDirectly(String? familyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFamilyIdDirectly,
          [familyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getFamilyIdByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getFamilyIdByEmail,
          [email],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i9.UserModel?> getUserModel(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserModel,
          [userId],
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<List<_i9.UserModel>> getFamilyMembers() => (super.noSuchMethod(
        Invocation.method(
          #getFamilyMembers,
          [],
        ),
        returnValue: _i4.Future<List<_i9.UserModel>>.value(<_i9.UserModel>[]),
      ) as _i4.Future<List<_i9.UserModel>>);

  @override
  _i4.Future<_i9.UserModel?> getUserById(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<_i9.UserModel?> getFamilyCreator() => (super.noSuchMethod(
        Invocation.method(
          #getFamilyCreator,
          [],
        ),
        returnValue: _i4.Future<_i9.UserModel?>.value(),
      ) as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Future<void> updateRelationship(
    String? userId,
    String? relationship,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRelationship,
          [
            userId,
            relationship,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> assignRoles(
    String? userId,
    List<String>? roles,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignRoles,
          [
            userId,
            roles,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisplayNameFromAuth() => (super.noSuchMethod(
        Invocation.method(
          #updateDisplayNameFromAuth,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> selfAssignAdminRole() => (super.noSuchMethod(
        Invocation.method(
          #selfAssignAdminRole,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reauthenticateUser(String? password) => (super.noSuchMethod(
        Invocation.method(
          #reauthenticateUser,
          [password],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCurrentUserAccount({
    String? password,
    bool? skipFirestoreDeletion = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCurrentUserAccount,
          [],
          {
            #password: password,
            #skipFirestoreDeletion: skipFirestoreDeletion,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserData(
    String? userId,
    String? familyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserData,
          [
            userId,
            familyId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFamilyData(String? familyId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFamilyData,
          [familyId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCollectionRecursive(String? collectionPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCollectionRecursive,
          [collectionPath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUserNotifications() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserNotifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resetDatabaseForCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #resetDatabaseForCurrentUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsubscribeFromChessTopic() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromChessTopic,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
