// Mocks generated by Mockito 5.4.4 from annotations
// in familyhub_mvp/test/services/privacy_filter_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:familyhub_mvp/models/extended_family_hub_data.dart' as _i6;
import 'package:familyhub_mvp/models/hub.dart' as _i2;
import 'package:familyhub_mvp/models/hub_invite.dart' as _i3;
import 'package:familyhub_mvp/services/extended_family_hub_service.dart' as _i4;
import 'package:familyhub_mvp/services/hub_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHub_0 extends _i1.SmartFake implements _i2.Hub {
  _FakeHub_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHubInvite_1 extends _i1.SmartFake implements _i3.HubInvite {
  _FakeHubInvite_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExtendedFamilyHubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtendedFamilyHubService extends _i1.Mock
    implements _i4.ExtendedFamilyHubService {
  MockExtendedFamilyHubService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.ExtendedFamilyHubData?> getExtendedFamilyData(String? hubId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExtendedFamilyData,
          [hubId],
        ),
        returnValue: _i5.Future<_i6.ExtendedFamilyHubData?>.value(),
      ) as _i5.Future<_i6.ExtendedFamilyHubData?>);

  @override
  _i5.Future<void> updateExtendedFamilyData(
    String? hubId,
    _i6.ExtendedFamilyHubData? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExtendedFamilyData,
          [
            hubId,
            data,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setRelationship(
    String? hubId,
    String? memberId,
    _i6.RelationshipType? relationship,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRelationship,
          [
            hubId,
            memberId,
            relationship,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setPrivacyLevel(
    String? hubId,
    String? memberId,
    _i6.PrivacyLevel? privacyLevel,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setPrivacyLevel,
          [
            hubId,
            memberId,
            privacyLevel,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMemberRole(
    String? hubId,
    String? memberId,
    _i6.ExtendedFamilyRole? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMemberRole,
          [
            hubId,
            memberId,
            role,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> inviteExtendedFamilyMember({
    required String? hubId,
    required String? email,
    _i6.RelationshipType? relationship,
    _i6.PrivacyLevel? privacyLevel = _i6.PrivacyLevel.minimal,
    _i6.ExtendedFamilyRole? role = _i6.ExtendedFamilyRole.viewer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteExtendedFamilyMember,
          [],
          {
            #hubId: hubId,
            #email: email,
            #relationship: relationship,
            #privacyLevel: privacyLevel,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.Hub>> getExtendedFamilyHubs() => (super.noSuchMethod(
        Invocation.method(
          #getExtendedFamilyHubs,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Hub>>.value(<_i2.Hub>[]),
      ) as _i5.Future<List<_i2.Hub>>);

  @override
  _i5.Future<bool> canViewContent(
    String? hubId,
    String? contentType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #canViewContent,
          [
            hubId,
            contentType,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [HubService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHubService extends _i1.Mock implements _i7.HubService {
  MockHubService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Hub>> getUserHubs() => (super.noSuchMethod(
        Invocation.method(
          #getUserHubs,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Hub>>.value(<_i2.Hub>[]),
      ) as _i5.Future<List<_i2.Hub>>);

  @override
  _i5.Future<_i2.Hub?> getHub(String? hubId) => (super.noSuchMethod(
        Invocation.method(
          #getHub,
          [hubId],
        ),
        returnValue: _i5.Future<_i2.Hub?>.value(),
      ) as _i5.Future<_i2.Hub?>);

  @override
  _i5.Future<_i2.Hub> createHub({
    required String? name,
    required String? description,
    String? icon,
    _i2.HubType? hubType = _i2.HubType.family,
    Map<String, dynamic>? typeSpecificData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createHub,
          [],
          {
            #name: name,
            #description: description,
            #icon: icon,
            #hubType: hubType,
            #typeSpecificData: typeSpecificData,
          },
        ),
        returnValue: _i5.Future<_i2.Hub>.value(_FakeHub_0(
          this,
          Invocation.method(
            #createHub,
            [],
            {
              #name: name,
              #description: description,
              #icon: icon,
              #hubType: hubType,
              #typeSpecificData: typeSpecificData,
            },
          ),
        )),
      ) as _i5.Future<_i2.Hub>);

  @override
  _i5.Future<_i2.Hub> ensureMyFriendsHub() => (super.noSuchMethod(
        Invocation.method(
          #ensureMyFriendsHub,
          [],
        ),
        returnValue: _i5.Future<_i2.Hub>.value(_FakeHub_0(
          this,
          Invocation.method(
            #ensureMyFriendsHub,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Hub>);

  @override
  _i5.Future<void> addMember(
    String? hubId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [
            hubId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeMember(
    String? hubId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            hubId,
            userId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateHub(
    String? hubId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateHub,
          [
            hubId,
            updates,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteHub(String? hubId) => (super.noSuchMethod(
        Invocation.method(
          #deleteHub,
          [hubId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.HubInvite> createInvite({
    required String? hubId,
    String? email,
    String? phoneNumber,
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createInvite,
          [],
          {
            #hubId: hubId,
            #email: email,
            #phoneNumber: phoneNumber,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<_i3.HubInvite>.value(_FakeHubInvite_1(
          this,
          Invocation.method(
            #createInvite,
            [],
            {
              #hubId: hubId,
              #email: email,
              #phoneNumber: phoneNumber,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<_i3.HubInvite>);

  @override
  _i5.Future<_i3.HubInvite?> getInvite(String? inviteId) => (super.noSuchMethod(
        Invocation.method(
          #getInvite,
          [inviteId],
        ),
        returnValue: _i5.Future<_i3.HubInvite?>.value(),
      ) as _i5.Future<_i3.HubInvite?>);

  @override
  _i5.Future<void> acceptInvite(String? inviteId) => (super.noSuchMethod(
        Invocation.method(
          #acceptInvite,
          [inviteId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.HubInvite>> getPendingInvitesForUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingInvitesForUser,
          [],
        ),
        returnValue: _i5.Future<List<_i3.HubInvite>>.value(<_i3.HubInvite>[]),
      ) as _i5.Future<List<_i3.HubInvite>>);
}
