// File generated by FlutterFire CLI or manually configured
// For web support, add your Firebase web config here

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Android config is read from google-services.json automatically
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnHlg-5GNajYwXWrtVLRJvOpkV0UEFcV4',
    appId: '1:559662117534:android:a59145c8a69587aee7c18f',
    messagingSenderId: '559662117534',
    projectId: 'family-hub-71ff0',
    storageBucket: 'family-hub-71ff0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy',
    appId: '1:559662117534:ios:dummy',
    messagingSenderId: '559662117534',
    projectId: 'family-hub-71ff0',
    storageBucket: 'family-hub-71ff0.firebasestorage.app',
    iosBundleId: 'com.example.familyhubMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy',
    appId: '1:559662117534:ios:dummy',
    messagingSenderId: '559662117534',
    projectId: 'family-hub-71ff0',
    storageBucket: 'family-hub-71ff0.firebasestorage.app',
    iosBundleId: 'com.example.familyhubMvp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_WWJtrIRRMvRyjMe7WaeYQ0veE9cs-Mw',
    appId: '1:559662117534:web:8bbba24544f83763e7c18f',
    messagingSenderId: '559662117534',
    projectId: 'family-hub-71ff0',
    authDomain: 'family-hub-71ff0.firebaseapp.com',
    storageBucket: 'family-hub-71ff0.firebasestorage.app',
    measurementId: 'G-6QGKDKVZ4D',
  );
}

